sudo: required
addons:
  chrome: stable
  
language: python
python:
  - "3.5"
dist: trusty
addons:
  chrome: stable

before_install:
  - pip install -r requirements.txt
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d test/driver/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

# command to run tests
script:
    - pytest
