language: python
python:
    - "3.5"

# command to install dependencies
install:
    - pip install -r requirements.txt

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

before_script:
  - gem install chromium
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

# command to run tests
script:
    - pytest
